# Generated by Django 4.2.3 on 2024-04-29 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('ism', models.CharField(max_length=200)),
                ('familya', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password1', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8)])),
                ('password2', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
        ),
    ]
