# Generated by Django 4.2.3 on 2024-05-29 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tavar_nomi_tavar_mijoz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mijoz',
            name='maxsulot',
        ),
        migrations.RemoveField(
            model_name='tavar',
            name='nom',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Mijoz',
        ),
        migrations.DeleteModel(
            name='Tavar',
        ),
        migrations.DeleteModel(
            name='Tavar_nomi',
        ),
    ]
